---
apiVersion: v1
kind: Namespace
metadata:
  name: http-server
  labels:
    app: http-server
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: http-server
  name: cpu-limit-range
  labels:
    app: http-servers
spec:
  limits:
    - default:
        cpu: "1"
      defaultRequest:
        cpu: "0.5"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: http-server
  name: mem-limit-range
  labels:
    app: http-server
spec:
  limits:
    - default:
        memory: 512Mi
      defaultRequest:
        memory: 256Mi
      type: Container
---
apiVersion: v1
kind: Service
metadata:
  namespace: http-server
  name: http-server
  labels:
    app: http-server
spec:
  type: NodePort
  selector:
    app: http-server
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: http-server
  name: http-server
  labels:
    app: http-server
spec:
  selector:
    matchLabels:
      app: http-server
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: http-server
          image: sawasy-http-server
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Never
          readinessProbe:
            exec:
              command: ["sh", "-c", "curl -s http://localhost:80/ | grep Well"]
            initialDelaySeconds: 3
          livenessProbe:
            exec:
              command: ["sh", "-c", "curl -s http://localhost:80/healthcheck | grep OK"]
            initialDelaySeconds: 3
          resources:
            requests:
              memory: "0.25Gi"
            limits:
              memory: "0.25Gi"